name = "cf-workers-starter"
main = "src/worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

# Uncomment if you have a build script.
# [build]
# command = "npm run build"

# Application Enviromnet
[vars]
copyright = 'Blaine Harper'
siteTitle = 'Cloudflare Starter Worker'
url = 'https://book.blaineharper.com'