name = "cf-workers-starter"
main = "src/worker.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[dev]
port=8787

# Uncomment if you have a build script.
# [build]
# command = "npm run build"

# Application Enviromnet
[vars]
BASE_URL = 'https://cf-workers-starter.blaineharper.com'

[env.dev]
vars = { BASE_URL='http://localhost:8787' }